# Generated by Django 5.2.12 on 2026-03-12 16:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('red', 'Red Team'), ('blue', 'Blue Team'), ('system', 'System')], max_length=10)),
                ('agent_name', models.CharField(max_length=100)),
                ('decision', models.TextField()),
                ('reasoning', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('outcome', models.TextField(blank=True, default='')),
                ('outcome_success', models.BooleanField(null=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'AI Decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('red', 'Red Team'), ('blue', 'Blue Team'), ('system', 'System')], max_length=10)),
                ('agent_name', models.CharField(max_length=100)),
                ('action_name', models.CharField(max_length=200)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_type', 'created_at'], name='core_agenta_agent_t_118cba_idx'), models.Index(fields=['round_id'], name='core_agenta_round_i_a2af74_idx')],
            },
        ),
    ]
