# Generated by Django 5.2.12 on 2026-03-24 14:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(db_index=True, max_length=100)),
                ('agent_type', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=10)),
                ('memory_type', models.CharField(choices=[('attack_success', 'Successful Attack'), ('attack_failure', 'Failed Attack'), ('defense_success', 'Successful Defense'), ('defense_failure', 'Failed Defense'), ('evasion', 'Evasion Tactic'), ('detection', 'Detection Pattern'), ('strategy', 'Strategic Insight'), ('adaptation', 'Adaptation Record')], max_length=20)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_port', models.IntegerField(blank=True, null=True)),
                ('target_service', models.CharField(blank=True, default='', max_length=200)),
                ('action_taken', models.CharField(max_length=200)),
                ('action_parameters', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('outcome_details', models.TextField(blank=True, default='')),
                ('reward', models.FloatField(default=0.0)),
                ('lesson', models.TextField(blank=True, default='', help_text='What the agent learned from this experience')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Searchable tags: ['port_scan', 'ssh', 'evasion']")),
                ('context_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('strength', models.FloatField(default=1.0, help_text='Memory strength, decays over time (0.0-1.0)')),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('simulation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_name', 'memory_type'], name='core_memory_agent_n_a97a6f_idx'), models.Index(fields=['agent_type', 'success'], name='core_memory_agent_t_38c81e_idx'), models.Index(fields=['target_service', 'action_taken'], name='core_memory_target__bb3ec5_idx')],
            },
        ),
    ]
