# Generated by Django 5.2.12 on 2026-03-12 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('nmap_tcp', 'Nmap TCP Scan'), ('nmap_udp', 'Nmap UDP Scan'), ('nmap_vuln', 'Nmap Vulnerability Scan'), ('nikto', 'Nikto Web Scan'), ('gobuster', 'Gobuster Directory Scan'), ('service_enum', 'Service Enumeration')], max_length=20)),
                ('target_ip', models.GenericIPAddressField()),
                ('target_port_range', models.CharField(blank=True, default='1-10000', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Raw scan output as JSON')),
                ('open_ports', models.JSONField(blank=True, default=list, help_text='List of open port dicts')),
                ('services', models.JSONField(blank=True, default=list, help_text='Discovered services')),
                ('os_detection', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_ip', 'scan_type'], name='red_team_sc_target__facdee_idx'), models.Index(fields=['status'], name='red_team_sc_status_5f57be_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttackPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_ip', models.GenericIPAddressField()),
                ('plan_data', models.JSONField(default=dict, help_text='Structured attack plan from LLM')),
                ('plan_text', models.TextField(blank=True, default='', help_text='Human-readable plan summary')),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(blank=True, null=True)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('llm_reasoning', models.TextField(blank=True, default='')),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='red_team.scanresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='medium', max_length=10)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('affected_service', models.CharField(blank=True, default='', max_length=200)),
                ('affected_port', models.IntegerField(blank=True, null=True)),
                ('detection_method', models.CharField(choices=[('cve_match', 'CVE Pattern Match'), ('llm_analysis', 'LLM Analysis'), ('nmap_script', 'Nmap Script'), ('manual', 'Manual'), ('ml_detection', 'ML Detection')], max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='Detection confidence 0.0-1.0')),
                ('remediation', models.TextField(blank=True, default='')),
                ('raw_evidence', models.JSONField(blank=True, default=dict)),
                ('exploitable', models.BooleanField(null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='red_team.scanresult')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExploitAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exploit_type', models.CharField(choices=[('metasploit', 'Metasploit Module'), ('sqlmap', 'SQLMap Injection'), ('custom', 'Custom Exploit'), ('bruteforce', 'Brute Force'), ('fuzzing', 'Fuzzing')], max_length=15)),
                ('target_ip', models.GenericIPAddressField()),
                ('target_port', models.IntegerField(blank=True, null=True)),
                ('target_service', models.CharField(blank=True, default='', max_length=200)),
                ('exploit_module', models.CharField(blank=True, default='', help_text='e.g. exploit/windows/smb/ms17_010_eternalblue', max_length=300)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked by Defense'), ('aborted', 'Aborted')], default='planned', max_length=10)),
                ('output', models.TextField(blank=True, default='')),
                ('session_obtained', models.BooleanField(default=False)),
                ('access_level', models.CharField(blank=True, default='', help_text='e.g. user, root, system', max_length=50)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploit_attempts', to='red_team.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='red_team_vu_severit_e148f9_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cve_id'], name='red_team_vu_cve_id_055db4_idx'),
        ),
        migrations.AddIndex(
            model_name='exploitattempt',
            index=models.Index(fields=['target_ip', 'status'], name='red_team_ex_target__45c5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='exploitattempt',
            index=models.Index(fields=['exploit_type'], name='red_team_ex_exploit_b12863_idx'),
        ),
    ]
