# Generated by Django 5.2.12 on 2026-03-12 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=15)),
                ('target_ips', models.JSONField(default=list, help_text='List of target IPs')),
                ('max_rounds', models.IntegerField(default=10)),
                ('round_duration_seconds', models.IntegerField(default=300)),
                ('red_team_config', models.JSONField(blank=True, default=dict)),
                ('blue_team_config', models.JSONField(blank=True, default=dict)),
                ('total_rounds_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('red_team', 'Red Team Active'), ('blue_team', 'Blue Team Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('red_team_scans', models.IntegerField(default=0)),
                ('red_team_vulns_found', models.IntegerField(default=0)),
                ('red_team_exploits_attempted', models.IntegerField(default=0)),
                ('red_team_exploits_succeeded', models.IntegerField(default=0)),
                ('blue_team_alerts', models.IntegerField(default=0)),
                ('blue_team_detections', models.IntegerField(default=0)),
                ('blue_team_blocks', models.IntegerField(default=0)),
                ('blue_team_false_positives', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('red_team_score', models.FloatField(default=0.0)),
                ('blue_team_score', models.FloatField(default=0.0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='simulation.simulationconfig')),
            ],
            options={
                'ordering': ['simulation', 'round_number'],
                'unique_together': {('simulation', 'round_number')},
            },
        ),
    ]
