# Generated by Django 5.2.12 on 2026-03-12 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rule_type', models.CharField(choices=[('signature', 'Signature'), ('anomaly', 'Anomaly Threshold'), ('behavioral', 'Behavioral Pattern')], max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_content', models.TextField(help_text='Rule definition (YARA/Snort syntax or JSON)')),
                ('enabled', models.BooleanField(default=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('hit_count', models.IntegerField(default=0)),
                ('false_positive_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('source', models.CharField(choices=[('ids', 'Intrusion Detection System'), ('anomaly_ml', 'ML Anomaly Detection'), ('signature', 'Signature Match'), ('log_analysis', 'Log Analysis'), ('traffic_monitor', 'Traffic Monitor')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, default='', max_length=10)),
                ('signature_id', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(default=0.5)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'status'], name='blue_team_a_severit_0f3695_idx'), models.Index(fields=['source_ip'], name='blue_team_a_source__6a97dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='TCP', max_length=10)),
                ('packet_size', models.IntegerField(default=0)),
                ('flags', models.CharField(blank=True, default='', max_length=20)),
                ('payload_preview', models.TextField(blank=True, default='', max_length=500)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_ip', 'timestamp'], name='blue_team_t_source__d419dd_idx'), models.Index(fields=['is_anomalous'], name='blue_team_t_is_anom_cb8f24_idx')],
            },
        ),
        migrations.CreateModel(
            name='DefenseAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('block_ip', 'Block IP Address'), ('rate_limit', 'Rate Limit'), ('honeypot', 'Deploy Honeypot'), ('isolate', 'Isolate Host'), ('patch', 'Apply Patch'), ('alert_admin', 'Alert Administrator'), ('update_rules', 'Update Detection Rules'), ('quarantine', 'Quarantine')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=15)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.TextField(blank=True, default='')),
                ('reasoning', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.5)),
                ('auto_generated', models.BooleanField(default=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('round_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='blue_team.alert')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'status'], name='blue_team_d_action__2c4fac_idx')],
            },
        ),
    ]
